workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 30
    instance_type: mac_mini_m1

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - yashrochlani7@gmail.com
